spring:
  datasource:
    url: jdbc:mysql://localhost:3306/getit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${GETIT_DB_USER:getit}
    password: ${GETIT_DB_PASSWORD:getit}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  thymeleaf:
    cache: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

app:
  jwt:
    secret: ${GETIT_JWT_SECRET:change-me-please-32-bytes-minimum-secret}
    expirationMinutes: 120
  geocoding:
    provider: none